[package]
name = "growthbook-rust-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }

reqwest = { version = "0.12.4", default-features = false, features = ["json", "rustls-tls"] }
reqwest-middleware = { version = "0.3.1" }

serde = { version = "1.0.196", features = ["derive"] }
serde_json = { version = "1.0.113", features = ["preserve_order"] }

reqwest-tracing = { version = "0.5.0", features = ["opentelemetry_0_21"] }
tracing = { version = "0.1.40" }

[dev-dependencies]
tokio = { version = "1.37.0", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }

rstest = { version = "0.20.0" }
test-context = { version = "0.3.0" }

wiremock = { version = "0.6.0" }

rand = { version = "0.8.5" }
uuid = { version = "1.8.0", features = ["v7", "serde"] }