# doc: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
max_width = 200
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
fn_params_layout = "Vertical"
fn_single_line = true
format_strings = true
force_multiline_blocks = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0