# doc: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
max_width = 200
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
fn_params_layout = "Vertical"
match_block_trailing_comma = true
use_field_init_shorthand = true